name: 'official plugin with jwt'
on: push
jobs:
  fetch_secrets:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Fetch static secrets from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.1.6
        id: fetch-secrets
        with:
          access-id: p-sq9mxbj4flltos
          access-type: jwt
          api-url: http://localhost:8000/api/v2
          static-secrets: |
            - name: "/l123"
              output-name: "my_secret"
